export const pagesRoutes = [
  ["v-4a3bd48a","/in.html",{"y":"p","t":"使用向导","i":"circle-info"},[":md"]],
  ["v-184f4da6","/intro.html",{"y":"p","t":"自己紹介","i":"circle-info"},[":md"]],
  ["v-8daa1a0e","/",{"y":"h","t":"主页","i":"fa-solid fa-house"},["/README.md"]],
  ["v-fb9569b6","/docs/main.html",{"y":"a","t":""},[":md"]],
  ["v-36173dce","/utau/basic.html",{"d":1700956800000,"l":"2023年11月26日","v":"/assets/images/cover3.jpg","e":"<p>在上个章节中我们已经完成了OpenUtau的基本配置，现在是时候让我们来解决<mark>主播我的Utau为什么发不出声的问题了</mark>（误</p>\n<h2> 主界面</h2>\n<div class=\"hint-container tip\">\n<p class=\"hint-container-title\">提示</p>\n<p><span class=\"xingmu\"><strong>详细介绍注意！！！</strong></span></p>\n<p>这里会介绍主界面的各个元素的作用，虽然个人来讲比较建议你都了解一下再上手，但是如果你觉得你完全看一眼就知道这些要怎么用，那你完全可以直接跳到下面的<a href=\"#%E5%BC%80%E5%A7%8B%E8%B0%83%E5%A3%B0%EF%BC%81\">开始调声！</a>部分。</p>\n<p><s>毕竟这个部分确实稍微有些长</s></p>\n</div>","y":"a","t":"基础操作入门","i":"fa-solid fa-music","O":3},[":md"]],
  ["v-6c4c99d6","/utau/flags.html",{"d":1700611200000,"l":"2023年11月22日","v":"/assets/images/cover3.jpg","y":"a","t":"Flag的使用","i":"fa-solid fa-flag","O":5},[":md"]],
  ["v-58aa66ac","/utau/from.html",{"d":1700611200000,"l":"2023年11月22日","v":"/assets/images/cover3.jpg","e":"<div class=\"hint-container info\">\n<p class=\"hint-container-title\">相关信息</p>\n<p><span class=\"xingmu\"><strong>这是什么？</strong></span></p>\n<p>Utau/泛音声合成社区能有如今的繁盛，有赖于每一位给后来人留下宝贵经验和资料的作者的贡献。</p>\n<p>也正是这样的共享精神使我们在这里相遇。</p>\n<p>在这里，我将编写过程中参考过的所有国内外资料及其页面对应的超链接和作者都进行列出，也许风云流转之后这里的资料最终也会慢慢消失在互联网的某个角落里不再能够被访问，但是这不会抹消掉每一个人的贡献。</p>\n<p><strong>互 联 网 精 神 天 下 第 一 ！</strong></p>\n</div>","y":"a","t":"引用来源&可参考资料","i":"fa-solid fa-share-from-square","O":9},[":md"]],
  ["v-1569f423","/utau/",{"d":1700611200000,"l":"2023年11月22日","v":"/assets/images/cover3.jpg","e":"<div class=\"hint-container tip\">\n<p class=\"hint-container-title\">提示</p>\n<p>当前版本的教程更新于： 2023年11月25日</p>\n<p>这并不是严谨的文档，更多只是个人对一些踩过的坑的经验之谈，也方便更多喜欢这些东西想要参与进创作的同志们能够少走一些弯路</p>\n</div>\n<div class=\"hint-container note\">\n<p class=\"hint-container-title\">编者注</p>\n<p>这系列文档的内容并非编者独创，相反，它们大多来源于社群中的其他文章作者和p主们的贡献，编者更多只是起到了整理的作用，当然也塞进去了一些个人的见解和经验，希望这些内容能够对后来者有所帮助，也希望后来者能继续将这份来自社群的互联网精神传递下去，为其他人分享经验，提供帮助。</p>\n<p><a href=\"/utau/from\">所有被引用的社群文章 -- &gt;</a></p>\n</div>","y":"a","t":"事先准备","i":"fa-solid fa-dumbbell"},["/utau/index.md"]],
  ["v-349f3bc1","/utau/install.html",{"d":1700870400000,"l":"2023年11月25日","v":"/assets/images/cover3.jpg","e":"<div class=\"hint-container note\">\n<p class=\"hint-container-title\">注</p>\n<p>本篇文档主要演示在<code>Windows</code>系统下的安装和配置过程，对于Linux用户，你应当知道如何使用Github Release上的Linux预编译版本。\nMacOS我也想讲，奈何买不起Mac（泪目）</p>\n</div>\n<div class=\"hint-container info\">\n<p class=\"hint-container-title\">相关信息</p>\n<p>截止本篇文档最后一次被编辑时的OpenUtau正式发行版本为 <a href=\"https://github.com/stakira/OpenUtau/releases/tag/build%2F0.1.158\" target=\"_blank\" rel=\"noopener noreferrer\">V0.1.158</a> Release。尽管不同版本的操作一般并不会有什么太大的区别，但我仍然建议你优先根据实际情况进行操作。</p>\n<p>如果一直没有跟进版本那么欢迎评论区催更~</p>\n</div>","y":"a","t":"安装OpenUtau","i":"fa-solid fa-download","O":2},[":md"]],
  ["v-092e7941","/utau/pit.html",{"d":1700611200000,"l":"2023年11月22日","v":"/assets/images/cover3.jpg","y":"a","t":"Pit It！","i":"fa-solid fa-wave-square","O":5},[":md"]],
  ["v-569264dc","/utau/plugins.html",{"d":1700611200000,"l":"2023年11月22日","v":"/assets/images/cover3.jpg","y":"a","t":"插件索引","i":"fa-solid fa-plug","O":7},[":md"]],
  ["v-3a249a67","/utau/resampler.html",{"d":1700611200000,"l":"2023年11月22日","v":"/assets/images/cover3.jpg","y":"a","t":"引擎设置","i":"fa-solid fa-car-battery","O":4},[":md"]],
  ["v-93147c58","/utau/skills.html",{"d":1700611200000,"l":"2023年11月22日","v":"/assets/images/cover3.jpg","y":"a","t":"一些调声技巧","i":"fa-solid fa-fill-drip","O":8},[":md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-147825fb","/docs/",{"y":"p","t":"Docs"},[]],
  ["v-5bc93818","/category/",{"y":"p","t":"分类","I":0},[]],
  ["v-744d024e","/tag/",{"y":"p","t":"标签","I":0},[]],
  ["v-e52c881c","/article/",{"y":"p","t":"文章","I":0},[]],
  ["v-154dc4c4","/star/",{"y":"p","t":"收藏","I":0},[]],
  ["v-01560935","/timeline/",{"y":"p","t":"时间轴","I":0},[]],
]
